name: Python
on:
    push:
      branches:
        - 'main'
      paths:
        - 'python/**'
        - '.github/workflows/**'
    pull_request:
      paths:
        - 'python/**'
        - '.github/workflows/**'

jobs:
  e2e-testing:
    strategy:
      matrix:
        python-version: ["3.12.x"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.7.1"

      - name: Install the project dependencies
        working-directory: python
        run: poetry build

      - name: List wheels
        working-directory: python
        run: python -c "import os; print('\n'.join(os.listdir('dist')))"
      
      - name: Install magika
        working-directory: python
        run: python -m pip install $(python -c "import glob; print(glob.glob('dist/magika-*.whl')[0])")
        shell: bash # Allows for cross-platform

      - name: Run magika with tests_data
        run: magika -r tests_data/ || exit 1
